env:
  global:
    - CC_TEST_REPORTER_ID=d946fbe840359053ee5604eb18d4cd53c9da50bb2e6af66191385e49962be152
sudo: false
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-9.0.1.0
  - rbx-3
env:
  # this doesn't do anything for MRI or RBX, but it doesn't hurt them either
  # for JRuby, it enables us to get more accurate coverage data
  - JRUBY_OPTS="--debug"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
